version: '3.5'

services:
  elasticsearch-node1:
    restart: always
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    deploy:
     replicas: 1
     restart_policy:
      condition: on-failure
    ports:
     - "9200:9200"
     - "9300:9300"
    environment:     
     - SERVICE_NAME=elasticsearch
     - SERVICE_TAGS=db,elasticsearch
     - SERVICE_REGION=DC1
     - discovery.type=single-node
  kibana:
    restart: always
    image: docker.elastic.co/kibana/kibana:7.4.0
    deploy:
     replicas: 1
     restart_policy:
      condition: on-failure
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=["http://elasticsearch-node1:9200"]
      - SERVICE_NAME=kibana
      - SERVICE_TAGS=apm
      - SERVICE_REGION=DC1